#! /bin/sh
pulseaudio --start 
killall sxhkd; sxhkd &
killall picom; picom -b --experimental-backends & 
killall polybar; polybar ws & polybar tray & polybar music &
#polybar tray &


setxkbmap -model abnt2 -layout br -variant abnt2
#feh --bg-fill Pictures/ug9p0ejs3j051.jpg
#feh --bg-fill Pictures/Wallpapers/1559689811981.jpg
#feh --bg-fill ~/Pictures/auroraalaska_alsop_big.jpg
#feh --bg-fill ~/Pictures/jjj1.jpg
#feh --bg-fill Pictures/sylvain-sarrailh-williametteartstation.jpg
#feh --bg-fill Pictures/Albert_Bierstadt_2.jpg
#feh --bg-fill Pictures/724742.jpg
#feh --bg-fill ~/Pictures/southcarolinaeclipseashleymarando.jpg 
#feh --bg-fill --random ~/Pictures/photo95cielaustral2048.jpg 
#feh --bg-fill ~/Pictures/869088.jpg 
#feh --bg-fill ~/Pictures/724875.jpg
#feh --bg-fill ~/Pictures/love_and\ war.jpg 
#feh --bg-fill ~/Pictures/ConjunctionColoursPhilHart.jpg 
#feh --bg-fill ~/Pictures/1512544219166.jpg
#feh --bg-fill ~/Pictures/ngc1333_noao_big.jpg
#feh --bg-fill ~/Pictures/HaloWinMoon48_claro.jpg 
#feh --bg-fill ~/Pictures/lazar-kiss-mark-R3exRpD17k0-unsplash.jpg
#feh --bg-fill  ~/Pictures/DarkDunesMars_Curiosity_9091.jpg
#feh --bg-fill  ~/Pictures/index.jpg 
#feh --bg-fill  ~/Pictures/LaSuperba_parkercarboni.jpg
#feh --bg-fill  ~/Pictures/lazar-kiss-mark-R3exRpD17k0-unsplash.jpg 
#feh --bg-fill  ~/Pictures/724875.jpg 
#feh --bg-fill  ~/Pictures/hood-river-autumn-2019.jpg
#feh --bg-fill  ~/Pictures/Desktop\ A.png
#feh --bg-fill  ~/Pictures/goldenfiled.png
#feh --bg-scale  ~/Pictures/eren.png
#feh --bg-fill  ~/Pictures/oceanlight.png
#feh --bg-fill  ~/Pictures/memaloose.jpg
#feh --bg-fill  ~/Pictures/Watermark_1594709716337.jpg
#feh --bg-scale  ~/Pictures/gq44im8qg8h51.jpg 
#feh --bg-fill  ~/Pictures/alex-h-pflaum-NQELNMBFt1U-unsplash.jpg
#feh --bg-fill  ~/Pictures/dark-rose.jpg
#feh --bg-fill  ~/Pictures/nathan-anderson-n4yHrZMh5b0-unsplash.jpg
#feh --bg-fill ~/Pictures/dark-rose.jpg 
#feh --bg-center  ~/Pictures/gab3.jpg
#feh --bg-fill ~/Pictures/DSC00979.jpg 
#feh --bg-fill ~/Pictures/lex-sirikiat-S8QtPzxdGUU-unsplash.jpg 
#feh --bg-center DSC00944.jpg
#feh --bg-fill ~/Pictures/joshua-newton-8z9pi6GgOo4-unsplash.jpg 
#feh --bg-fill --random ~/Pictures/dave-hoefler-DVauUHIJby0-unsplash.jpg
#feh --bg-fill ~/Pictures/dave1.jpg  
#feh --bg-fill --random ~/Pictures/dave-hoefler-hBhfEXkihOs-unsplash1.jpg
#feh --bg-fill --random ~/Pictures/Mountainous_Landscape_by_Moonlight_1871_Albert_Bierstadt.jpg 
#feh --bg-fill --random ~/Pictures/wp4694540-pixels-art-wallpapers.png
#feh --bg-fill --random ~/Pictures/suganth-KBfkJkd-jIM-unsplash.jpg
#feh --bg-fill --random ~/Pictures/pawel-czerwinski-Q28mUd2RdoQ-unsplash.jpg
#feh --bg-fill --random ~/Pictures/fernando-rodrigues-sGJUb5HJBqs-unsplash.jpg
#feh --bg-fill --random ~/Pictures/hudson-hintze-SXSYjCgUo9Y-unsplashl.jpg 
#feh --bg-fill --random ~/Pictures/vivek-doshi-yJWa6kcGlAE-unsplash.jpg 
#feh --bg-fill --random ~/Pictures/halowinmoon2.jpg
#feh --bg-fill --random ~/Pictures/hudson-hintze-SXSYjCgUo9Y-unsplashl.jpg
#feh --bg-fill --random ~/Pictures/albert3.jpg   
#feh --bg-fill --random ~/Pictures/jonathan-knepper-p3VTsifODg8-unsplash.jpg
#feh --bg-fill --random ~/Pictures/jonathan-knepper-tiPlWlug2qE-unsplash.jpg 
#feh --bg-fill --random ~/Pictures/mat-reding-QmomtSxIkzA-unsplash.jpg  
#feh --bg-fill --random 0001.png
#feh --bg-fill --random ~/Pictures/marko-blazevic-S7mAngnWV1A-unsplash.jpg
#feh --bg-fill --random ~/Pictures/rocco-caruso-OUiuOn2s7VE-unsplash.jpg
#feh --bg-fill --random ~/Pictures/jessica-fadel-xCIUbJzLroI-unsplash.jpg 
#feh --bg-fill --random ~/Pictures/em-be-khoc-nhe-hNzOqY2KY0M-unsplash.jpg
#feh --bg-fill --random ~/Pictures/alex-ware-mJfgC-E6E6M-unsplash.jpg
#feh --bg-fill --random ~/Pictures/alex-h-pflaum-NQELNMBFt1U-unsplash.jpg 
#feh --bg-fill --random ~/Pictures/griffin-wooldridge-bppfsnSN5dI-unsplash.jpg
feh --bg-fill --random ~/Pictures/peter-hulce-VjRDxGS_R-4-unsplash.jpg



xsetroot -cursor_name left_ptr &
xset r rate 200 75

#### MONITORS ####
bspc monitor -d      term web code book campground music moon omega all misc



#### BSPWM configuration ####
#bspc config border_radius                8

bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner




bspc config border_width 0
bspc config window_gap 10
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config swallow_first_click true


#### BSPWM coloring #

bspc config normal_border_color '#2A2525'
bspc config active_border_color '#494343'
bspc config focused_border_color '#494343'


#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr


#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a brave-beta desktop='^2' state=tiled follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a 'Spotify' desktop='music' follow=on
bspc rule -a Zathura state=tiled
bspc rule -a inkscape state=floating

bspc rule -a neomutt desktop='^8' state=tiled follow=on


